#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Run from the repo root so Info.plist and .env land in the right place.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

RELEASE_DOMAIN="releases.shidou.dev"
R2_BUCKET_NAME="shidou-releases"
INFO_PLIST="resources/Info.plist"

banner "Shidou release setup"

# ── Stage 1: prerequisites ────────────────────────────────────────────────
stage "Prerequisites"
say "Checking the tools this wizard and the release pipeline need."
missing=0
for tool in gh bun plutil security xcrun base64; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "✓ $tool"
  else
    warn "missing: $tool"
    missing=1
  fi
done
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  note "✓ gh is authenticated"
else
  warn "gh is not authenticated — run 'gh auth login' first; secret writes will be skipped otherwise"
fi
if ! command -v rclone >/dev/null 2>&1; then
  warn "rclone missing (only needed for local 'bun run release'); brew install rclone"
fi
[[ "$missing" -eq 1 ]] && warn "install the missing tools, then re-run this wizard"
pause

# ── Stage 2: Sparkle update keys ──────────────────────────────────────────
stage "Sparkle update keys"
say "Shidou updates are signed with an EdDSA key. The public half goes in"
say "$INFO_PLIST as SUPublicEDKey; the private half becomes the"
say "SPARKLE_PRIVATE_KEY GitHub secret. Losing the private key permanently"
say "breaks updates for every install, so back it up."
GENERATE_KEYS=""
for candidate in .shidou-cache/sparkle/*/bin/generate_keys; do
  [[ -x "$candidate" ]] && GENERATE_KEYS="$candidate"
done
if [[ -z "$GENERATE_KEYS" ]] && [[ -n "${SPARKLE_BIN:-}" && -x "$SPARKLE_BIN/generate_keys" ]]; then
  GENERATE_KEYS="$SPARKLE_BIN/generate_keys"
fi
if [[ -z "$GENERATE_KEYS" ]]; then
  warn "Sparkle's generate_keys was not found under .shidou-cache/sparkle/."
  say "It appears there after any bundled build. Either:"
  step "run: ./scripts/bundle.sh debug   (in another terminal), or"
  step "download Sparkle from https://github.com/sparkle-project/Sparkle/releases,"
  say "  unpack it, and re-run this wizard with SPARKLE_BIN=<path-to-its-bin>."
  SKIPPED+=("Sparkle keys: generate_keys not found; re-run this wizard after a build")
  pause "Press Enter to continue without Sparkle keys for now"
else
  note "using $GENERATE_KEYS"
  say "Generating (or reusing) the key in your login keychain..."
  "$GENERATE_KEYS" || true
  SPARKLE_PUBLIC_KEY=$("$GENERATE_KEYS" -p | tail -n1 | tr -d '[:space:]')
  if [[ -z "$SPARKLE_PUBLIC_KEY" ]]; then
    warn "could not read the public key from generate_keys -p"
    SKIPPED+=("Sparkle keys: generate_keys -p returned nothing")
  else
    note "public key: $SPARKLE_PUBLIC_KEY"
    plutil -replace SUPublicEDKey -string "$SPARKLE_PUBLIC_KEY" "$INFO_PLIST"
    printf '  %s✓ wrote%s SUPublicEDKey → %s\n' "$GREEN" "$RESET" "$INFO_PLIST"
    # generate_keys -x refuses an existing file, so hand it a fresh path
    # inside a private directory rather than a pre-created mktemp file.
    key_dir=$(mktemp -d)
    key_file="$key_dir/sparkle_private_key"
    if "$GENERATE_KEYS" -x "$key_file" && [[ -s "$key_file" ]]; then
      set_secret SPARKLE_PRIVATE_KEY "$(cat "$key_file")"
      warn "Back up the private key NOW: it is in your login keychain under"
      say "  the Sparkle 'Private key for signing updates' item. Save it to your"
      say "  password manager before continuing."
    else
      warn "could not export the private key"
      SKIPPED+=("GitHub secret SPARKLE_PRIVATE_KEY: export failed; run generate_keys -x and gh secret set by hand")
    fi
    rm -rf "$key_dir"
    pause "Backed up? Press Enter to continue"
  fi
fi

# ── Stage 3: Developer ID certificate ─────────────────────────────────────
stage "Apple Developer ID certificate"
say "CI signs the macOS app with your Developer ID Application certificate,"
say "imported from a base64-encoded .p12 export."
say ""
say "If you don't have the certificate yet:"
open_url "https://developer.apple.com/account/resources/certificates/list"
step "Create a 'Developer ID Application' certificate and install it locally."
say ""
say "Then export it: open Keychain Access → My Certificates, right-click the"
step "'Developer ID Application: …' certificate → Export → .p12, set a password."
ask P12_PATH "Path to the exported .p12 file:"
P12_PATH="${P12_PATH/#\~/$HOME}"
if [[ ! -f "$P12_PATH" ]]; then
  warn "file not found: $P12_PATH"
  SKIPPED+=("APPLE_CERTIFICATE / APPLE_CERTIFICATE_PASSWORD: .p12 not provided")
else
  ask_secret P12_PASSWORD "Password you set on the .p12:"
  set_secret APPLE_CERTIFICATE "$(base64 < "$P12_PATH")"
  set_secret APPLE_CERTIFICATE_PASSWORD "$P12_PASSWORD"
fi
say ""
say "Your signing identities:"
security find-identity -v -p codesigning | sed 's/^/    /' || true
ask SHIDOU_SIGNING_IDENTITY "Identity to sign with (e.g. 'Developer ID Application: Your Name (TEAMID)'):"
write_env SHIDOU_SIGNING_IDENTITY "$SHIDOU_SIGNING_IDENTITY"
set_secret SHIDOU_SIGNING_IDENTITY "$SHIDOU_SIGNING_IDENTITY"

# ── Stage 4: notarization credentials ─────────────────────────────────────
stage "Notarization (Apple ID)"
say "CI notarizes the DMG with notarytool, which needs your Apple ID, your"
say "team ID, and an app-specific password."
ask APPLE_ID "Apple ID email used for your developer account:"
ask APPLE_TEAM_ID "Apple Team ID (10 characters, shown at developer.apple.com → Membership):"
open_url "https://account.apple.com/account/manage"
step "Sign in → App-Specific Passwords → Generate one named 'shidou-ci'."
ask_secret APPLE_APP_SPECIFIC_PASSWORD "Paste the app-specific password:"
set_secret APPLE_ID "$APPLE_ID"
set_secret APPLE_TEAM_ID "$APPLE_TEAM_ID"
set_secret APPLE_APP_SPECIFIC_PASSWORD "$APPLE_APP_SPECIFIC_PASSWORD"
say ""
if confirm "Also store these as the local 'NOTARY' keychain profile for 'bun run release'?"; then
  xcrun notarytool store-credentials NOTARY \
    --apple-id "$APPLE_ID" \
    --password "$APPLE_APP_SPECIFIC_PASSWORD" \
    --team-id "$APPLE_TEAM_ID" || warn "store-credentials failed; run it by hand later"
fi

# ── Stage 5: Cloudflare R2 bucket + domain ────────────────────────────────
stage "Cloudflare R2 bucket + release domain"
say "Releases are served from an R2 bucket behind $RELEASE_DOMAIN."
open_url "https://dash.cloudflare.com/?to=/:account/r2/new"
step "Create a bucket named exactly: $R2_BUCKET_NAME"
pause "Bucket created? Press Enter"
step "Open the bucket → Settings → Custom Domains → Connect Domain."
step "Attach: $RELEASE_DOMAIN  (the zone shidou.dev must be on this account)"
say "Cloudflare adds the DNS record for you when the zone is on the account."
pause "Domain attached? Press Enter"

# ── Stage 6: R2 API token ─────────────────────────────────────────────────
stage "R2 API token"
say "The sync-release workflow uploads release assets to the bucket with an"
say "S3-style API token."
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
step "Create API Token → 'Object Read & Write', scoped to $R2_BUCKET_NAME."
step "Copy the Access Key ID, the Secret Access Key, and your Account ID"
say "  (the account ID is in the R2 API endpoint / right sidebar)."
ask R2_ACCOUNT_ID "Cloudflare account ID:"
ask R2_ACCESS_KEY_ID "Access Key ID:"
ask_secret R2_SECRET_ACCESS_KEY "Secret Access Key:"
set_secret R2_ACCOUNT_ID "$R2_ACCOUNT_ID"
set_secret R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
set_secret R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"
set_secret R2_BUCKET "$R2_BUCKET_NAME"
if command -v rclone >/dev/null 2>&1; then
  if rclone listremotes 2>/dev/null | grep -q '^r2:'; then
    note "rclone remote 'r2' already exists; leaving it alone"
  elif confirm "Create the local rclone remote 'r2' for 'bun run release'?"; then
    rclone config create r2 s3 \
      provider=Cloudflare \
      access_key_id="$R2_ACCESS_KEY_ID" \
      secret_access_key="$R2_SECRET_ACCESS_KEY" \
      endpoint="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" \
      no_check_bucket=true >/dev/null \
      && printf '  %s✓ created%s rclone remote r2\n' "$GREEN" "$RESET" \
      || warn "rclone config failed; see RELEASING.md for the manual remote"
  fi
fi

# ── Stage 7: analytics (optional) ─────────────────────────────────────────
stage "Analytics (optional)"
say "The macOS build embeds an analytics endpoint and website ID"
say "(Umami-style). Skip this if you don't run analytics; the app builds"
say "fine without it."
if confirm "Configure analytics?"; then
  ask SHIDOU_ANALYTICS_ENDPOINT "Analytics endpoint URL:"
  ask SHIDOU_ANALYTICS_WEBSITE_ID "Analytics website ID:"
  write_env SHIDOU_ANALYTICS_ENDPOINT "$SHIDOU_ANALYTICS_ENDPOINT"
  write_env SHIDOU_ANALYTICS_WEBSITE_ID "$SHIDOU_ANALYTICS_WEBSITE_ID"
  set_secret SHIDOU_ANALYTICS_ENDPOINT "$SHIDOU_ANALYTICS_ENDPOINT"
  set_secret SHIDOU_ANALYTICS_WEBSITE_ID "$SHIDOU_ANALYTICS_WEBSITE_ID"
else
  note "skipped; CI passes empty values and the build embeds nothing"
fi

# ── Stage 8: Windows code signing (optional) ──────────────────────────────
stage "Windows code signing (optional)"
say "With no Authenticode certificate, CI still builds Windows installers —"
say "they are just unsigned (SmartScreen warns on first run)."
if confirm "Configure a Windows .pfx certificate?"; then
  ask PFX_PATH "Path to the Authenticode .pfx file:"
  PFX_PATH="${PFX_PATH/#\~/$HOME}"
  if [[ -f "$PFX_PATH" ]]; then
    ask_secret PFX_PASSWORD "Password for the .pfx:"
    set_secret WINDOWS_CERTIFICATE "$(base64 < "$PFX_PATH")"
    set_secret WINDOWS_CERTIFICATE_PASSWORD "$PFX_PASSWORD"
  else
    warn "file not found: $PFX_PATH"
    SKIPPED+=("WINDOWS_CERTIFICATE / WINDOWS_CERTIFICATE_PASSWORD: .pfx not provided")
  fi
else
  note "skipped; Windows builds will be unsigned"
fi

finish
say "Next: commit the SUPublicEDKey change to $INFO_PLIST, then cut a release"
say "by bumping the version in Cargo.toml and pushing a v<version> tag"
say "(see RELEASING.md)."
